const workflowConfig = {
  mainland: [
    "KYC & Background Check",
    "Business Activity Selection",
    "Trade Name Reservation",
    "Legal Structure Confirmation",
    "Initial Approval / Pre-Approval",
    "MoA Drafting & Signature",
    "Office Lease / Flexi Desk",
    "Payment & License Issuance",
    "Establishment Card",
    "Visa Allocation Request",
    "Visa Application",
    "Medical & Emirates ID",
    "Corporate Tax Registration",
    "VAT Registration",
    "Bank Account Setup",
    "Chamber of Commerce Registration",
  ],
  freezone: [
    "KYC & Background Check",
    "Business Activity Selection",
    "Trade Name Reservation",
    "Legal Structure Confirmation",
    "Initial Approval / Pre-Approval",
    "MoA Drafting & Signature",
    "Office Lease / Flexi Desk",
    "Payment & License Issuance",
    "Establishment Card",
    "Visa Allocation Request",
    "Visa Application",
    "Medical & Emirates ID",
    "Corporate Tax Registration",
    "VAT Registration",
    "Bank Account Setup",
    "Chamber of Commerce Registration",
  ],
  offshore: [
    "KYC & Background Check",
    "Business Activity Selection",
    "Trade Name Reservation",
    "Legal Structure Confirmation",
    "Initial Approval / Pre-Approval",
    "MoA Drafting & Signature",
    "Payment & License Issuance",
    "Corporate Tax Registration",
    "VAT Registration",
    "Bank Account Setup",
    "Registered Agent Appointment",
  ],
};

export default workflowConfig;
